In [ ]:
import time
import numpy as np

In [ ]:
x = np.random.random (100000000)

In [ ]:
#Case 1
start = time.time()
sum(x) / len(x)
print (time.time() - start)

8.585712194442749


In [ ]:
#Case 2
start = time.time()
np.mean(x)
print(time.time() - start)

0.07424616813659668


#Creating NumPy ndarrays

##1.	Using regular Python lists

In [ ]:
import numpy as np

#rank 1 array
x = np.array([1, 2, 3, 4, 5])
#to get array rank
x.ndim

1

In [ ]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#returns datatypes of the elements in the array
#shows the memory occupation 
x.dtype

dtype('int64')

In [ ]:
#.shape returns a tuple reprsenting the array dimension
#(rows, columns)
x.shape

(5,)

In [ ]:
#rank 2 array
y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
y.shape

(4, 3)

In [ ]:
#.size gives total number of elements of the array
y.size

12

In [ ]:
x = np.array(['Hello', 'World'])
print (x)

['Hello' 'World']


In [ ]:
#U5 stands for unicode strings of 5 characters
print('shape', x.shape)
print('type', type(x))
print('dtype', x.dtype)

shape (2,)
type <class 'numpy.ndarray'>
dtype <U5


In [ ]:
#Upcasting
#Array data must be treated as the same datatype and thus here, unicode
x = np.array([1, 2, 'World'])
print(x)
print('shape', x.shape)
print('type', type(x))
print('dtype', x.dtype)

['1' '2' 'World']
shape (3,)
type <class 'numpy.ndarray'>
dtype <U21


In [ ]:
x = np.array([1, 2.5, 4])
print(x, x.dtype)

[1.  2.5 4. ] float64


In [ ]:
x = np.array([1.5, 2.2, 3.7], dtype=np.int64)
print(x)
print('dtype', x.dtype)

[1 2 3]
dtype int64


In [ ]:
#.save save the array into a file with the give name
x = np.array([1, 2, 3, 4, 5])
np.save('my_array', x)

In [ ]:
#.load loads the file
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]


##Practice

In [ ]:
import numpy as np

# create numpy array of letters a-j
letter_array = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print("Letter Array: ", letter_array)

# get dtype of array
print('dtype:', letter_array.dtype)


# get shape of array
print('shape:', letter_array.shape)

Letter Array:  ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']
dtype: <U1
shape: (10,)


##2.	Using built-in NumPy functions

In [ ]:
#.zeros create array of zeros with datatype float63
x = np.zeros((3, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print('dtype', x.dtype)

dtype float64


In [ ]:
x = np.zeros((3, 4), dtype = int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
print('dtype', x.dtype)

dtype int64


In [ ]:
x = np.ones((4, 5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#.full((,), num) autofill the array with the given value
x = np.full((4, 3), 5)
print (x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
#Identity Matrix
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#Diagonal Matrix
x = np.diag([10, 20, 30, 50])
print(x)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


In [ ]:
#.arange(start, end, step) creates 1D array of evenly spaced values 
#within a given interval
#only integers value
x = np.arange(10)
print(x)
y = np.arange(4, 10)
print(y)
z = np.arange(1, 14, 3)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[ 1  4  7 10 13]


In [ ]:
#.alinspace(start, end, n) non-integer values
#must take at least 2 values
#n default is 50
x = np.linspace(0, 25, 10)
print(x)
y = np.linspace(0, 25, 10, endpoint=False)
print(y)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [ ]:
#.reshape changes the rank of the array
#checks if the number of values is suitable for the give new shape
#else, it will release an error
x = np.arange(20)
print(x)
x = np.reshape(x, (4,5))
print (x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
x = np.reshape(x, (10,2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [ ]:
y = np.arange(20).reshape((10, 2))
print (y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [ ]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [ ]:
x = np.random.random((3, 3))
print(x)

[[0.2716747  0.73965268 0.49517487]
 [0.58364526 0.59805429 0.85919013]
 [0.7020565  0.01117212 0.0156169 ]]


In [ ]:
#(upper_bound, lower_bound, shape)
x = np.random.randint(4, 15, (3, 2))
print(x)

[[6 7]
 [8 8]
 [5 8]]


In [ ]:
#random values from normal distribution 
#(mean, standard deviation, size)
x = np.random.normal(0, 0.1, size=(1000, 1000))
print(x)

[[ 0.10957844 -0.04786357  0.1493487  ... -0.1546417   0.03773197
   0.08371709]
 [ 0.05121261  0.0062681   0.02641147 ...  0.05112616  0.03315038
  -0.02527392]
 [-0.09390247  0.03948246 -0.00544424 ... -0.01492499 -0.13226261
   0.1003579 ]
 ...
 [ 0.01202138 -0.08908256 -0.06413172 ... -0.31107236 -0.00212517
  -0.02456408]
 [ 0.09269404  0.0288718  -0.196394   ...  0.09403025 -0.03711007
  -0.02444978]
 [ 0.08924099 -0.11168459 -0.0157433  ...  0.10837867  0.04540839
  -0.00259068]]


In [ ]:
print('mean', x.mean())
print('std', x.std())
print('max', x.max())
print('min', x.min())
print('# positive', (x > 0).sum())
print('# negative', (x < 0).sum())

mean 0.000166194349507901
std 0.10007517028614624
max 0.44404978105374177
min -0.4583095235543712
# positive 500799
# negative 499201


##Practice

In [ ]:
import numpy as np

# Using the Built-in functions you learned about on the
# previous page, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

X = np.arange(2, 34, 2).reshape(4, 4)
print(X)

Y = np.linspace(2, 34, 16).reshape(4, 4)
print(Y)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
[[ 2.          4.13333333  6.26666667  8.4       ]
 [10.53333333 12.66666667 14.8        16.93333333]
 [19.06666667 21.2        23.33333333 25.46666667]
 [27.6        29.73333333 31.86666667 34.        ]]


#Accessing, Deleting, and Inserting Elements Into ndarrays

In [2]:
import numpy as np

In [3]:
#ndarrays are mutable, and can be sliced
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [5]:
print('1st element:', x[0])
print('2nd element:', x[1])
print('3rd element:', x[2])

1st element: 1
2nd element: 2
3rd element: 3


In [6]:
print('1st element:', x[-5])
print('1st element:', x[-4])
print('5th element:', x[-1])

1st element: 1
1st element: 2
5th element: 5


In [7]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [9]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print('Element at (0, 0):', x[0, 0])
print('Element at (0, 1):', x[0, 1])
print('Element at (2, 2):', x[2, 2])

Element at (0, 0): 1
Element at (0, 1): 2
Element at (2, 2): 9


In [11]:
x[0, 0] = 20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [15]:
#Delete from rank 1 array
x = np.array([1, 2 ,3 , 4, 5])
print(x)

#(array, [indices])
x = np.delete(x, [0, 4])
print(x)

[1 2 3 4 5]
[2 3 4]


In [16]:
#Delete from rank 2 array
#axis=0 selects rows, axis= selects column
y = np.arange(1, 10).reshape(3, 3)
print(y)

w = np.delete(y, 0, axis=0)
print('\n', w)

v = np.delete(y, [0, 2], axis=1)
print('\n', v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [18]:
#Adding values using .append(array, [indices], axis) function
#Append in rank 1 array
x = np.array([1, 2 ,3 , 4, 5])
print(x)

x = np.append(x, 6)
print(x)

x = np. append (x, [7, 8])
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]


In [22]:
#Append in rank 2 array
y = np.arange(1, 10).reshape(3, 3)
print(y)

#Append row (axis=0)
w = np.append(y, [[10, 11, 12]], axis=0)
print('\n',w)

#Append column (axis=1)
v = np.append (y, [[10], [11], [12]], axis=1)
print('\n', v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [24]:
#Insert values to arrays in specific place
# .insert(array, index, element, axis)
#Insert in 1 rank array
x = np.array([1, 2, 5, 6, 7])
print(x)

x = np.insert(x, 2, [3, 4])
print('\n', x)

[1 2 5 6 7]

 [1 2 3 4 5 6 7]


In [26]:
#Insert in 2 rank array
y = np.array([[1, 2, 3], [7, 8, 9]])
print(y)

w = np.insert(y, 1, [4, 5, 6], axis=0)
print('\n', w)

v = np.insert(y, 1, 5, axis=1)
print('\n', v)

[[1 2 3]
 [7 8 9]]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[1 5 2 3]
 [7 5 8 9]]


In [31]:
#NumPy allows stacking arrays on top of each other or side by side
#using .vstack() for vertical stacking or .hstack() for horizontal stacking
#The shapes of the arrays must match for stacking to happen

x = np.array([1, 2])
print(x)

y = np.array([[3, 4], [5, 6]])
print('\n', y)

v = np.vstack((x, y))
print('\n', v)

h = np.hstack((y, x.reshape(2, 1)))
print('\n', h)

[1 2]

 [[3 4]
 [5 6]]

 [[1 2]
 [3 4]
 [5 6]]

 [[3 4 1]
 [5 6 2]]


#Slicing ndarrays

In [32]:
import numpy as np

In [36]:
#helps in accessing subsets of arrays
#ndarray[start:end]
#ndarray[start:]
#ndarray[:end]

X = np.arange(1, 21).reshape(4, 5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [37]:
#[rows, columns]
x = X[1:4, 2:5]
print(x)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [38]:
x = X[1:, 2:]
print(x)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [39]:
x = X[:3, 2:]
print(x)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [41]:
x = X[:, 2]
print(x)

[ 3  8 13 18]


In [42]:
x = X[:, 2:3]
print(x)

[[ 3]
 [ 8]
 [13]
 [18]]


In [43]:
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [44]:
z = X[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [45]:
z[2, 2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [46]:
#If change in subset, it will change in the entire array
print(X)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


In [47]:
X = np.arange(20).reshape(4, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [48]:
#Copy helps in reserving the original data by creating a new nparray
#completely independent from the original
#copy as function
x = np.copy(X[1:, 2:])
print(x)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [50]:
#copy as method
x = X[1:, 2:].copy()
print(x)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [51]:
x[2, 2] = 555
print(x)

[[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]


In [53]:
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [54]:
#using an array as indices to do something
indices = np.array([1, 3])
print(indices)

[1 3]


In [55]:
y = X[indices, :]
print(y)

[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [56]:
z = X[:, indices]
print(z)

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [58]:
#extracting elements from the diagonal of the array
#by default, k=0
x = np.diag(X)
print(x)

[ 0  6 12 18]


In [59]:
#printing diagonal above main diagonal by setting k
x = np.diag(X, k=1)
print(x)

[ 1  7 13 19]


In [60]:
#printing diagonal below main diagonal by setting k
x = np.diag(X, k=-1)
print(x)

[ 5 11 17]


In [62]:
#getting unique values from the array
X = np.array([[1, 2, 3], [5, 2, 8], [1, 2, 3]]) 
print(X)

print('\n', np.unique(X))

[[1 2 3]
 [5 2 8]
 [1 2 3]]

 [1 2 3 5 8]


#Boolean Indexing, Set Operations, and Sorting

In [63]:
import numpy as np

In [65]:
X = np.arange(25).reshape(5, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [66]:
#using boolean indexing to get specific values under condition
#ex values greater than
print(X[X>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [67]:
#using boolean indexing to change values in array
X[(X >10) & (X <17)] = -1
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [69]:
#set operations for comparing np arrays
#for intersection, union, difference
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [75]:
#sort np arrays
#when sort is used as a function, it is stored in memory out of place
#original array doen't change

x = np.random.randint(1, 11, size=(10, ))
print(np.sort(x))
print(x)

[1 1 2 3 3 5 5 6 7 9]
[9 7 3 5 1 2 3 6 5 1]


In [76]:
print(np.sort(np.unique(x)))

[1 2 3 5 6 7 9]


In [77]:
#when sort is used as a method, it is stored in memory in place
#original array is changed

x.sort()
print(x)

[1 1 2 3 3 5 5 6 7 9]


In [78]:
#in rank 2 arrays, use axis to determine whether sorting is occured
#on rows or columns
X = np.random.randint(1, 11, size=(5, 5))
print(X)

[[ 3 10  8  2  7]
 [ 6  9  2  7  3]
 [ 8  7  3  6  1]
 [ 9  1  9  3  4]
 [ 9  2  9  3  1]]


In [79]:
#sort rank 2 on rows
print(np.sort(X, axis=0))

[[ 3  1  2  2  1]
 [ 6  2  3  3  1]
 [ 8  7  8  3  3]
 [ 9  9  9  6  4]
 [ 9 10  9  7  7]]


In [80]:
#sort rank 2 on columns
print(np.sort(X, axis=1))

[[ 2  3  7  8 10]
 [ 2  3  6  7  9]
 [ 1  3  6  7  8]
 [ 1  3  4  9  9]
 [ 1  2  3  9  9]]


##Practice

In [82]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).

# Afterwards use Boolean indexing to pick out only the odd numbers in the array

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1, 26).reshape(5, 5)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X%2 != 0]

print(X)
print(Y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


#Arithmetic Operations and Broadcasting

In [83]:
#numpy  allows element-wise operations on ndarrays 
#as well as matrix operations
#This part is for element-wise operations
import numpy as np

In [84]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [87]:
#can use arithmetic symbols or functions
print (x + y)
print(np.add(x, y))
print (x - y)
print(np.subtract(x, y))
print (x * y)
print(np.multiply(x, y))
print (x / y)
print(np.divide(x, y))

[ 6  8 10 12]
[ 6  8 10 12]
[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [89]:
#broadcasting is a term of handling element-wise arithmetic operations
#for different array shapes
#arithmatics must occur on arrays of same shape or broadcastable

X = np.array([1, 2, 3, 4]).reshape(2, 2)
Y = np.array([5, 6, 7, 8]).reshape(2, 2)
print(X)
print('\n', Y)

[[1 2]
 [3 4]]

 [[5 6]
 [7 8]]


In [91]:
print (X + Y)
print ('\n', X - Y)
print ('\n', X * Y)
print ('\n', X / Y)

[[ 6  8]
 [10 12]]

 [[-4 -4]
 [-4 -4]]

 [[ 5 12]
 [21 32]]

 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [92]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.        ]


In [93]:
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [94]:
print(np.power(x, 2))

[ 1  4  9 16]


In [95]:
#np has statistical functions such as mean
#mean of all array
print('average of all', X.mean())

average of all 2.5


In [97]:
#mean of rows
print('average of rows', X.mean(axis=1))

#mean of columns
print('average of columns', X.mean(axis=0))

average of rows [2. 3.]
average of columns [1.5 3.5]


In [98]:
#Statistical sum
print('sum of all', X.sum())
print('sum of columns', X.sum(axis=0))
print('sum of rows', X.sum(axis=1))

sum of all 10
sum of columns [4 6]
sum of rows [3 7]


In [99]:
X.std()

1.118033988749895

In [102]:
np.median(X)

2.5

In [103]:
X.max()

4

In [104]:
X.min()

1

In [105]:
#Do arithmatics without loops
#it broadcasts the value (3) to have the same shape as the array
print(3 + X)
print ('\n', X-3)
print ('\n', X*3)
print ('\n', X/3)

[[4 5]
 [6 7]]

 [[-2 -1]
 [ 0  1]]

 [[ 3  6]
 [ 9 12]]

 [[0.33333333 0.66666667]
 [1.         1.33333333]]


In [110]:
Y = np.arange(9).reshape(3, 3)
print (Y)

#array x will be broadcasted to be suitable for addition
"""
[[0 1 2]
 [0 1 2]
 [0 1 2]]
"""
x = np.arange(3)
print('\n', x)

print('\n', Y + x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [0 1 2]

 [[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [113]:
Y = np.arange(9).reshape(3, 3)
print (Y)

#array x will be broadcasted to be suitable for addition
"""
[[0 0 0]
 [1 1 1]
 [2 2 2]]
"""
x = np.arange(3).reshape(3,1)
print('\n', x)

print('\n', x + Y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[0]
 [1]
 [2]]

 [[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


#Practice

In [117]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

# Do not change the name of this array. 
# Please don't print anything from your code! The TEST RUN button below will print your array. 

X = np.arange(1, 5) * np.ones((4, 4))

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
